mapping map=([
 "/d/huashan/xianzhangya":"华山仙掌崖",
 "/d/huashan/yunvfeng":"华山玉女峰",
 "/d/huashan/wuyunfeng":"华山五云峰",
 "/d/huashan/xiaqiting":"华山下棋亭",
 "/d/wuyishan/shandong":"武夷山的山洞中",
 "/d/wuyishan/pubu":"武夷山的瀑布处",
 
 "/d/hengshan/yunge":"恒山云阁处",
 "/d/hengshan/zhanqiao":"恒山栈桥处",
 "/d/hengshan/jinlongxia":"恒山的金龙峡",
 "/d/hengshan/xuankong1":"恒山的悬空寺北楼",
 "/d/hengshan/xuankong2":"恒山的悬空寺南楼",
 "/d/hengshan/daziling":"恒山的大字岭",
 "/d/hengshan/hufengkou":"恒山的虎风口",
 "/d/hengshan/guolaoling":"恒山的果老岭",
 "/d/hengshan/beiyuemiao":"恒山的北岳庙",
 "/d/hengshan/kutianjing":"恒山的苦甜井",
 "/d/hengshan/huixiantai":"恒山的会仙台",
 "/d/hengshan/square":"恒山的见性峰",
 "/d/taishan/baihequan":"泰山的白鹤泉",
 "/d/taishan/hongmengong":"泰山的红门宫",
 "/d/taishan/doumugong":"泰山的斗母宫",
 "/d/taishan/hutiange":"泰山的壶天阁",
 "/d/taishan/yunbuqiao":"泰山的云步桥",
 "/d/taishan/bixiaci":"泰山的碧霞祠",
 "/d/taishan/yuhuangding":"泰山的玉皇顶",
 "/d/taishan/nantianmen":"泰山的南天门",
 "/d/clone/room/lingwu/jingzhai/wolong1":"长白山的卧龙岭",
 "/d/clone/room/lingwu/jingzhai/wolong2":"长白山的望天角",
 "/d/clone/room/lingwu/jingzhai/wolong3":"长白山的浮云坪",
 "/d/clone/room/lingwu/jingzhai/wolong4":"长白山的飞云崖",
 "/d/saiwai/shop":"塞外的燕原集",
 
 "/d/emeishan/pubu":"峨眉山的瀑布",
 "/d/emeishan/bifengxia":"峨眉山的碧峰峡",
 "/d/emeishan/jietuopo":"峨眉山的解脱坡",
 "/d/emeishan/jingxinan":"峨眉山的静心庵",
 "/d/emeishan/lianhuashi":"峨眉山的莲花石",
 "/d/emeishan/jingxinan":"峨眉山的静心庵",

 "/d/tuyuhun/silk1":"仇池山",
 "/d/tuyuhun/silk3":"颂摩崖",
 "/d/tuyuhun/silk5b":"兴隆山",
 "/d/chengdu/simiao":"成都大石寺",
 "/d/tuyuhun/silk3a":"鸣沙山",
 "/d/tuyuhun/silk3b":"万象洞",
 "/d/tuyuhun/silk3c":"月牙泉",
 "/d/tuyuhun/silk5a":"胭脂山",
 "/d/taiyuan/jiayuguan":"嘉峪关",
 
]);
